ugettext = lambda s: s

PERMISSION_CHOICES = ('portal', 'plugin')

APP_PERMISSION = {'portal': [('portal','updatelevel', ugettext('Change Player Level')),
                             ('portal','reglevel', ugettext('Give Player Regular Level')),
                             ('portal','userlevel', ugettext('Give Player Registered Level')),
                             ('portal','unreglevel', ugettext('Remove Regular Level')),
                             ('portal','unuserlevel', ugettext('Remove Registered Level')),
                             ('portal','viewfullip', ugettext('View Player Full IP')),
                             ('portal','viewclientinfo', ugettext('View Player Details')),
                             ('portal','viewadminsinfo', ugettext('View Admins Details')),
                             ('portal','viewclientgroup', ugettext('View Player Group')),
                             ('portal','addpenalty', ugettext('Add New Penalty')),
                             ('portal','editpenalty', ugettext('Edit Existing Penalty')),
                             ('portal','removepenalty', ugettext('Disable Penalty')),
                             ('portal','addnotice', ugettext('Add New Notice')),
                             ('portal','removenotice', ugettext('Remove Player Notice')),
                             ('portal','listadmins', ugettext('View Server Admins List')),
                             ('portal','listpenalties', ugettext('View Penalties')),
                             ('portal','viewguid', ugettext('View Player Real GUID')),
                             ('portal','viewalias', ugettext('View Player Aliases')),
                             ('portal','viewauditlogs', ugettext('View Audit Logs')),
                             ('portal','viewnotes', ugettext('View User Comments')),
                             ('portal','addnotes', ugettext('Add User Comments')),
                             ('portal','deletenotes', ugettext('Delete User Comments'))],
                  'plugin': [('chatlog','chatlog', ugettext('View Chat Records')),
                             ('auditor','view_adm_logs', ugettext('View Admin Activity')),
                             ('auditor','view_user_logs', ugettext('View User Activity')),
                             ('follow','viewfollow', ugettext('View Follow List')),
                             ('follow','addfollow', ugettext('Add Player To Follow List')),
                             ('follow','removefollow', ugettext('Remove Player From Follow List')),
                             ('status','viewstatus', ugettext('View Server Status'))]};

APP_GROUP_PERMISSION = [('Server Admin',['portal.viewfullip',
                                      'portal.viewclientinfo',
                                      'portal.unuserlevel',
                                      'portal.userlevel',
                                      'portal.viewalias',
                                      'portal.listpenalties',
                                      'portal.addnotice',
                                      'portal.viewnotes',
                                      'portal.addnotes',
                                      'portal.viewadminsinfo',
                                      'portal.viewclientgroup',
                                      'plugin.status.viewstatus',
                                      'plugin.follow.addfollow',
                                      'plugin.follow.viewfollow',
                                      'plugin.chatlog.chatlog']),
                        ('Server Full Admin',['portal.viewfullip',
                                      'portal.viewclientinfo',
                                      'portal.reglevel',
                                      'portal.userlevel',
                                      'portal.unreglevel',
                                      'portal.unuserlevel',
                                      'portal.viewalias',
                                      'portal.listpenalties',
                                      'portal.addnotice',
                                      'portal.addpenalty',
                                      'portal.editpenalty',
                                      'portal.removepenalty',
                                      'portal.removenotice',
                                      'portal.viewguid',
                                      'portal.viewadminsinfo',
                                      'portal.viewclientgroup',
                                      'portal.viewnotes',
                                      'portal.addnotes',
                                      'plugin.auditor.view_adm_logs',
                                      'plugin.auditor.view_user_logs',
                                      'plugin.status.viewstatus',
                                      'plugin.follow.viewfollow',
                                      'plugin.follow.addfollow',
                                      'plugin.follow.removefollow',
                                      'plugin.chatlog.chatlog']),
                        ]