PERMISSION_CHOICES = ('portal', 'plugin')

APP_PERMISSION = {'portal': [('portal','updatelevel', 'Change Player Level'),
                             ('portal','reglevel', 'Give Player Regular Level'),
                             ('portal','userlevel', 'Give Player User Level'),
                             ('portal','viewfullip', 'View Player Full IP'),
                             ('portal','viewclientinfo', 'View Player Details'),
                             ('portal','viewadminsinfo', 'View Admins Details'),
                             ('portal','viewclientgroup', 'View Player Group'),
                             ('portal','addpenalty','Add New Penalty'),
                             ('portal','editpenalty', 'Edit Existing Penalty'),
                             ('portal','removepenalty', 'Disable Penalty'),
                             ('portal','addnotice', 'Add New Notice'),
                             ('portal','removenotice','Remove Player Notice'),
                             ('portal','listadmins','View Server Admins List'),
                             ('portal','listpenalties','View General Penalties (warn, notice)'),
                             ('portal','viewguid','View Player Real GUID'),
                             ('portal','viewalias','View Player Aliases')],
                  'plugin': [('chatlog','chatlog','View Chat Records'),
                             ('follow','viewfollow','View Follow List'),
                             ('follow','addfollow','Add Player To Follow List'),
                             ('follow','removefollow','Remove Player From Follow List'),
                             ('status','viewstatus','View Server Status')]};

APP_GROUP_PERMISSION = [('Server Admin',['portal.viewfullip',
                                      'portal.viewclientinfo',
                                      'portal.reglevel',
                                      'portal.userlevel',
                                      'portal.viewalias',
                                      'portal.listpenalties',
                                      'portal.addnotice',
                                      'portal.viewclientgroup',
                                      'plugin.status.viewstatus',
                                      'plugin.follow.addfollow',
                                      'plugin.follow.viewfollow',
                                      'plugin.chatlog.chatlog']),
                        ('Server Full Admin',['portal.viewfullip',
                                      'portal.viewclientinfo',
                                      'portal.reglevel',
                                      'portal.userlevel',
                                      'portal.viewalias',
                                      'portal.listpenalties',
                                      'portal.addnotice',
                                      'portal.addpenalty',
                                      'portal.editpenalty',
                                      'portal.removepenalty',
                                      'portal.removenotice',
                                      'portal.viewguid',
                                      'portal.viewadminsinfo',
                                      'portal.viewclientgroup',
                                      'plugin.status.viewstatus',
                                      'plugin.follow.viewfollow',
                                      'plugin.follow.addfollow',
                                      'plugin.follow.removefollow',
                                      'plugin.chatlog.chatlog']),
                        ]