# PHPBB GROUP NAME / DJANGO GROUP NAME
from django.conf import settings
DEFAULT_GROUP_MAPPING = {'ADMINISTRATORS':'Admin'}
GROUP_MAPPING = getattr(settings, 'PHPBB_GROUP_MAPPING', DEFAULT_GROUP_MAPPING)